package modelo.entidades;
// Generated 28-10-2015 22:20:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String rutC;
     private Long telefono;
     private String email;
     private String direccion;
     private String nombre;
     private Set ordenTrabajos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String rutC) {
        this.rutC = rutC;
    }
    public Cliente(String rutC, Long telefono, String email, String direccion, String nombre, Set ordenTrabajos) {
       this.rutC = rutC;
       this.telefono = telefono;
       this.email = email;
       this.direccion = direccion;
       this.nombre = nombre;
       this.ordenTrabajos = ordenTrabajos;
    }
   
    public String getRutC() {
        return this.rutC;
    }
    
    public void setRutC(String rutC) {
        this.rutC = rutC;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getOrdenTrabajos() {
        return this.ordenTrabajos;
    }
    
    public void setOrdenTrabajos(Set ordenTrabajos) {
        this.ordenTrabajos = ordenTrabajos;
    }




}


