package modelo.entidades;
// Generated 28-10-2015 22:20:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private String imei;
     private String marca;
     private String modelo;
     private Set ordenTrabajos = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(String imei) {
        this.imei = imei;
    }
    public Equipo(String imei, String marca, String modelo, Set ordenTrabajos) {
       this.imei = imei;
       this.marca = marca;
       this.modelo = modelo;
       this.ordenTrabajos = ordenTrabajos;
    }
   
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Set getOrdenTrabajos() {
        return this.ordenTrabajos;
    }
    
    public void setOrdenTrabajos(Set ordenTrabajos) {
        this.ordenTrabajos = ordenTrabajos;
    }




}


