package modelo.entidades;
// Generated 28-10-2015 22:20:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrdenTrabajo generated by hbm2java
 */
public class OrdenTrabajo  implements java.io.Serializable {


     private long numOrden;
     private Cliente cliente;
     private Equipo equipo;
     private Personal personal;
     private Tienda tienda;
     private Date fechaIng;
     private Date fechaEnt;
     private long abono;
     private long total;
     private String descripObser;
     private String falla;
     private String diagnostico;
     private String estado;
     private String serie;

    public OrdenTrabajo() {
    }

	
    public OrdenTrabajo(long numOrden, Cliente cliente, Equipo equipo, Personal personal, Tienda tienda, Date fechaIng, Date fechaEnt, long abono, long total, String falla) {
        this.numOrden = numOrden;
        this.cliente = cliente;
        this.equipo = equipo;
        this.personal = personal;
        this.tienda = tienda;
        this.fechaIng = fechaIng;
        this.fechaEnt = fechaEnt;
        this.abono = abono;
        this.total = total;
        this.falla = falla;
    }
    public OrdenTrabajo(long numOrden, Cliente cliente, Equipo equipo, Personal personal, Tienda tienda, Date fechaIng, Date fechaEnt, long abono, long total, String descripObser, String falla, String diagnostico, String estado, String serie) {
       this.numOrden = numOrden;
       this.cliente = cliente;
       this.equipo = equipo;
       this.personal = personal;
       this.tienda = tienda;
       this.fechaIng = fechaIng;
       this.fechaEnt = fechaEnt;
       this.abono = abono;
       this.total = total;
       this.descripObser = descripObser;
       this.falla = falla;
       this.diagnostico = diagnostico;
       this.estado = estado;
       this.serie = serie;
    }
   
    public long getNumOrden() {
        return this.numOrden;
    }
    
    public void setNumOrden(long numOrden) {
        this.numOrden = numOrden;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public Date getFechaIng() {
        return this.fechaIng;
    }
    
    public void setFechaIng(Date fechaIng) {
        this.fechaIng = fechaIng;
    }
    public Date getFechaEnt() {
        return this.fechaEnt;
    }
    
    public void setFechaEnt(Date fechaEnt) {
        this.fechaEnt = fechaEnt;
    }
    public long getAbono() {
        return this.abono;
    }
    
    public void setAbono(long abono) {
        this.abono = abono;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public String getDescripObser() {
        return this.descripObser;
    }
    
    public void setDescripObser(String descripObser) {
        this.descripObser = descripObser;
    }
    public String getFalla() {
        return this.falla;
    }
    
    public void setFalla(String falla) {
        this.falla = falla;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }




}


