package modelo.entidades;
// Generated 28-10-2015 22:20:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private String rutP;
     private Tienda tienda;
     private String contrasena;
     private Character permiso;
     private String colores;
     private String titulo;
     private Long telefono;
     private String ayudacontrasena;
     private String nombre;
     private Set ordenTrabajos = new HashSet(0);

    public Personal() {
    }

	
    public Personal(String rutP, Tienda tienda) {
        this.rutP = rutP;
        this.tienda = tienda;
    }
    public Personal(String rutP, Tienda tienda, String contrasena, Character permiso, String colores, String titulo, Long telefono, String ayudacontrasena, String nombre, Set ordenTrabajos) {
       this.rutP = rutP;
       this.tienda = tienda;
       this.contrasena = contrasena;
       this.permiso = permiso;
       this.colores = colores;
       this.titulo = titulo;
       this.telefono = telefono;
       this.ayudacontrasena = ayudacontrasena;
       this.nombre = nombre;
       this.ordenTrabajos = ordenTrabajos;
    }
   
    public String getRutP() {
        return this.rutP;
    }
    
    public void setRutP(String rutP) {
        this.rutP = rutP;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Character getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(Character permiso) {
        this.permiso = permiso;
    }
    public String getColores() {
        return this.colores;
    }
    
    public void setColores(String colores) {
        this.colores = colores;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getAyudacontrasena() {
        return this.ayudacontrasena;
    }
    
    public void setAyudacontrasena(String ayudacontrasena) {
        this.ayudacontrasena = ayudacontrasena;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getOrdenTrabajos() {
        return this.ordenTrabajos;
    }
    
    public void setOrdenTrabajos(Set ordenTrabajos) {
        this.ordenTrabajos = ordenTrabajos;
    }




}


